In [33]:
import tensorflow as tf

In [34]:
print(tf.__version__)

2.0.0


In [35]:
from tensorflow.keras.datasets import mnist

In [36]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [48]:
print(train_images.shape)

(60000, 784)


In [49]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [50]:
train_images[0].ndim

1

In [51]:
train_images[0].shape

(784,)

In [41]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [42]:
from tensorflow.keras import layers, models

In [43]:
#1 Sequential, 2: Functional API
network = models.Sequential()

In [45]:
#Dense means fully connected
#activation: Convert linearity into non linearity
#last activation function is based on the problem
#softmax provides probability
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [46]:
#Compilation: Training Structure
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [47]:
#Normalize the data
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

In [52]:
#One Hot Encoding
from tensorflow.keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [53]:
#Training
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 7s 121us/sample - loss: 0.6866 - accuracy: 0.7757
Epoch 2/5
60000/60000 [==============================] - 7s 110us/sample - loss: 0.1568 - accuracy: 0.9601
Epoch 3/5
60000/60000 [==============================] - 8s 131us/sample - loss: 0.0942 - accuracy: 0.9751 - loss: 0.0941 - accu
Epoch 4/5
60000/60000 [==============================] - 8s 132us/sample - loss: 0.0686 - accuracy: 0.9815
Epoch 5/5
60000/60000 [==============================] - 8s 131us/sample - loss: 0.0522 - accuracy: 0.9863


In [54]:
#Testing
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [55]:
print(test_acc)

0.9742


In [56]:
network.predict(test_images)

array([[5.8008527e-06, 1.1301577e-04, 8.9171481e-05, ..., 9.9942124e-01,
        8.8950367e-09, 3.3363764e-04],
       [2.1081556e-13, 1.6134101e-05, 9.9956995e-01, ..., 3.3008491e-05,
        9.8354169e-09, 5.9139499e-08],
       [4.6095869e-10, 9.9935013e-01, 3.0452014e-05, ..., 9.8351456e-06,
        6.0729677e-04, 2.2986382e-09],
       ...,
       [8.3257992e-06, 2.1532281e-07, 2.3991008e-05, ..., 1.8247802e-06,
        1.4317668e-05, 9.6886368e-05],
       [7.7977774e-08, 1.5278689e-08, 2.2608204e-07, ..., 2.3143988e-07,
        3.5469211e-06, 3.2536787e-05],
       [2.6353253e-05, 2.1311901e-07, 1.3394509e-06, ..., 1.7685929e-08,
        8.9853520e-09, 3.0215854e-11]], dtype=float32)